id: IC4600240
source: https://library.bdrc.io
source_file: null
initial_creation_type: ocr
imported: '2020-03-21T23:40:10+00:00'
last_modified: '2022-06-07T16:16:33.385713+00:00'
parser: https://github.com/OpenPecha-dev/openpecha-toolkit/blob/231bba39dd1ba393320de82d4d08a604aabe80fc/openpecha/formatters/google_orc.py
source_metadata:
  id: bdr:W11757
  title: ཆོས་རྗེ་ནམ་མཁའ་སེང་གེའི་རྣམ་ཐར་དང་མན་ངག་ལྷན་ཐབས་ལྟར་གྱི་ཧ་ནུ་མན་ཐའི་རོལ་རྩེད།
  author: ''
  access: http://purl.bdrc.io/admindata/AccessOpen
  restrictedInChina: false
  base:
    '6999':
      image_group_id: I1KG21868
      title: ''
      total_pages: 284
      order: 1
      base_file: 6999.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
