id: P002929
initial_creation_type: ocr
source_metadata:
  id: bdr:W11757
  title: ཆོས་རྗེ་ནམ་མཁའ་སེང་གེའི་རྣམ་ཐར་དང་མན་ངག་ལྷན་ཐབས་ལྟར་གྱི་ཧ་ནུ་མན་ཐའི་རོལ་རྩེད།
  author: ''
  volumes:
    bdde8909a20248e2a801b18ae5a48c1d:
      image_group_id: I1KG21868
      title: ''
      volume_number: 1
      total_pages: 284
      base_file: v001.txt
